# Generated by Django 2.2.4 on 2020-01-14 04:11

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Genre',
            fields=[
                ('id', models.BigAutoField(db_column='id', primary_key=True, serialize=False)),
                ('name', models.CharField(db_column='name', max_length=120, unique=True)),
            ],
            options={
                'db_table': 'genre',
                'managed': True,
                'default_permissions': (),
            },
        ),
        migrations.CreateModel(
            name='Title',
            fields=[
                ('tconst', models.CharField(db_column='tconst', max_length=300, primary_key=True, serialize=False, unique=True)),
                ('primary_title', models.CharField(db_column='primary_title', max_length=300)),
                ('original_title', models.CharField(db_column='original_title', max_length=300)),
                ('is_adult', models.BooleanField(db_column='is_adult', default=False)),
                ('start_year', models.IntegerField(db_column='start_year')),
                ('end_year', models.IntegerField(db_column='end_year', null=True)),
                ('runtime_minutes', models.IntegerField(db_column='runtime_minutes')),
                ('genres', models.ManyToManyField(related_name='titles', to='title.Genre')),
            ],
            options={
                'db_table': 'title',
                'managed': True,
                'default_permissions': (),
            },
        ),
        migrations.CreateModel(
            name='TitleType',
            fields=[
                ('id', models.BigAutoField(db_column='id', primary_key=True, serialize=False)),
                ('name', models.CharField(db_column='name', max_length=100, unique=True)),
            ],
            options={
                'db_table': 'title_type',
                'managed': True,
                'default_permissions': (),
            },
        ),
        migrations.CreateModel(
            name='Profession',
            fields=[
                ('id', models.BigAutoField(db_column='id', primary_key=True, serialize=False)),
                ('name', models.CharField(db_column='name', max_length=120, unique=True)),
            ],
            options={
                'db_table': 'profession',
                'managed': True,
                'default_permissions': (),
            },
        ),
        migrations.CreateModel(
            name='Rating',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('average_rating', models.FloatField(db_column='average_rating')),
                ('num_votes', models.IntegerField(db_column='num_votes')),
                ('tconst', models.ForeignKey(db_column='tconst', db_index=False, on_delete=django.db.models.deletion.DO_NOTHING, related_name='rating', to='title.Title')),
            ],
            options={
                'db_table': 'rating',
                'managed': True,
                'default_permissions': (),
            },
        ),
        migrations.CreateModel(
            name='Person',
            fields=[
                ('nconst', models.CharField(db_column='nconst', max_length=300, primary_key=True, serialize=False, unique=True)),
                ('primary_name', models.CharField(db_column='primary_name', max_length=120)),
                ('birth_year', models.IntegerField(db_column='birth_year')),
                ('death_year', models.IntegerField(db_column='death_year', null=True)),
                ('know_for_titles', models.ManyToManyField(related_name='persons_titles', to='title.Title')),
                ('professions', models.ManyToManyField(related_name='persons_professions', to='title.Profession')),
            ],
            options={
                'db_table': 'person',
                'managed': True,
                'default_permissions': (),
            },
        ),
        migrations.AddField(
            model_name='title',
            name='type',
            field=models.ForeignKey(db_column='id_title_type', db_index=False, on_delete=django.db.models.deletion.DO_NOTHING, related_name='title', to='title.TitleType'),
        ),
    ]
