# Generated by Django 2.2.4 on 2020-01-15 03:23

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('title', '0001_initial_database'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='TitleType',
            new_name='Type',
        ),
        migrations.RemoveField(
            model_name='rating',
            name='id',
        ),
        migrations.AlterField(
            model_name='rating',
            name='tconst',
            field=models.OneToOneField(db_column='tconst', on_delete=django.db.models.deletion.DO_NOTHING, primary_key=True, related_name='rating', serialize=False, to='title.Title'),
        ),
        migrations.AlterField(
            model_name='title',
            name='runtime_minutes',
            field=models.IntegerField(db_column='runtime_minutes', null=True),
        ),
    ]
