# Generated by Django 2.2.4 on 2020-01-17 14:09

from django.db import migrations
from modules.read_file import ReadFile


def insert_data(apps, schema_editor):
    ReadFile.import_movies_data()
    ReadFile.import_names_data()


class Migration(migrations.Migration):
    dependencies = [
        ('title', '0001_initial_database'),
    ]

    operations = [
        migrations.RunPython(insert_data),
    ]
