# Generated by Django 2.2.4 on 2020-01-15 04:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('title', '0002_update_title_runtime_minutes'),
    ]

    operations = [
        migrations.AlterField(
            model_name='title',
            name='start_year',
            field=models.IntegerField(db_column='start_year', null=True),
        ),
    ]
