# Generated by Django 2.2.4 on 2020-01-15 04:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('title', '0003_update_title_start_year'),
    ]

    operations = [
        migrations.AlterField(
            model_name='person',
            name='birth_year',
            field=models.IntegerField(db_column='birth_year', null=True),
        ),
    ]
