# Generated by Django 2.2.4 on 2020-01-15 13:29

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('title', '0004_update_person_birth_year'),
    ]

    operations = [
        migrations.AlterField(
            model_name='title',
            name='type',
            field=models.ForeignKey(db_column='id_title_type', db_index=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='title', to='title.Type'),
        ),
    ]
