# Generated by Django 2.2.4 on 2020-01-16 04:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('title', '0005_update_nullable_fields'),
    ]

    operations = [
        migrations.AlterField(
            model_name='person',
            name='birth_year',
            field=models.IntegerField(db_column='birth_year', default=None, null=True),
        ),
        migrations.AlterField(
            model_name='person',
            name='death_year',
            field=models.IntegerField(db_column='death_year', default=None, null=True),
        ),
        migrations.AlterField(
            model_name='title',
            name='end_year',
            field=models.IntegerField(db_column='end_year', default=None, null=True),
        ),
        migrations.AlterField(
            model_name='title',
            name='runtime_minutes',
            field=models.IntegerField(db_column='runtime_minutes', default=None, null=True),
        ),
        migrations.AlterField(
            model_name='title',
            name='start_year',
            field=models.IntegerField(db_column='start_year', default=None, null=True),
        ),
    ]
